### ISSUE TITLE
Inactive keybindings still reserve their shortcut

### ISSUE THREAD

**Issue by klaa97** [mbnuqw/sidebery#241]
## Steps to reproduce
- Deactivate a shortcut
- Try to assign the command of the deactivated shortcut to another one

## Expected behavior
It should be possible to assign the shortcut, since the other one was deactivated.

## Actual behavior
The shortcut isn't assigned, as if the old one was still active.

I'm not a vue expert, but I think I found the origin of this: https://github.com/mbnuqw/sidebery/blob/b96cf58b70ff0f6c845b21391fa39040579ed4c9/src/page.settings/components/settings.keybindings.vue
In particular, in the function checkShortcut(), it isn't checked whether the shortcut is active or not.

## Environment info
OS: linux
Firefox: 76.0
Addon: 4.8.0

<details><code>
{
  "settings": {
    "version": "4.8.0",
    "nativeScrollbars": true,
    "selWinScreenshots": true,
    "tabsCheck": true,
    "tabsFix": "notify",
    "ctxMenuNative": true,
    "autoHideCtxMenu": 1000,
    "ctxMenuRenderInact": true,
    "navBarLayout": "horizontal",
    "navBarInline": false,
    "hideAddBtn": false,
    "hideSettingsBtn": true,
    "navBtnCount": false,
    "hideEmptyPanels": true,
    "navMidClickAction": "none",
    "navSwitchPanelsWheel": true,
    "groupLayout": "grid",
    "dndTabAct": true,
    "dndTabActDelay": 750,
    "dndTabActMod": "none",
    "dndExp": "pointer",
    "dndExpDelay": 0,
    "dndExpMod": "none",
    "stateStorage": "global",
    "warnOnMultiTabClose": "collapsed",
    "activateOnMouseUp": true,
    "activateLastTabOnPanelSwitching": true,
    "skipEmptyPanels": false,
    "showTabRmBtn": true,
    "showTabCtx": true,
    "hideInact": false,
    "activateAfterClosing": "next",
    "activateAfterClosingPrevRule": "visible",
    "activateAfterClosingNextRule": "tree",
    "activateAfterClosingGlobal": false,
    "activateAfterClosingNoFolded": false,
    "activateAfterClosingNoDiscarded": false,
    "shiftSelAct": true,
    "askNewBookmarkPlace": false,
    "tabsRmUndoNote": true,
    "nativeHighlight": false,
    "tabsUnreadMark": false,
    "tabsReloadLimit": 5,
    "moveNewTabPin": "start",
    "moveNewTabParent": "last_child",
    "moveNewTabParentActPanel": false,
    "moveNewTab": "end",
    "pinnedTabsPosition": "panel",
    "pinnedTabsList": false,
    "pinnedAutoGroup": true,
    "tabsTree": true,
    "groupOnOpen": true,
    "tabsTreeLimit": "none",
    "hideFoldedTabs": false,
    "autoFoldTabs": true,
    "autoFoldTabsExcept": "none",
    "autoExpandTabs": false,
    "rmChildTabs": "all",
    "tabsChildCount": true,
    "tabsLvlDots": true,
    "discardFolded": false,
    "discardFoldedDelay": 0,
    "discardFoldedDelayUnit": "sec",
    "tabsTreeBookmarks": true,
    "bookmarksPanel": true,
    "warnOnMultiBookmarkDelete": "collapsed",
    "openBookmarkNewTab": false,
    "midClickBookmark": "open_new_tab",
    "actMidClickTab": false,
    "autoCloseBookmarks": false,
    "autoRemoveOther": false,
    "highlightOpenBookmarks": false,
    "activateOpenBookmarkTab": false,
    "showBookmarkLen": false,
    "bookmarksRmUndoNote": true,
    "fontSize": "m",
    "bgNoise": true,
    "animations": false,
    "animationSpeed": "fast",
    "theme": "default",
    "style": "dark",
    "sidebarCSS": true,
    "groupCSS": false,
    "snapNotify": true,
    "snapExcludePrivate": false,
    "snapInterval": 0,
    "snapIntervalUnit": "min",
    "snapLimit": 0,
    "snapLimitUnit": "snap",
    "hScrollThroughPanels": false,
    "scrollThroughTabs": "none",
    "scrollThroughVisibleTabs": false,
    "scrollThroughTabsSkipDiscarded": false,
    "scrollThroughTabsExceptOverflow": true,
    "scrollThroughTabsCyclic": false,
    "tabDoubleClick": "none",
    "tabLongLeftClick": "none",
    "tabLongRightClick": "none",
    "tabsPanelLeftClickAction": "none",
    "tabsPanelDoubleClickAction": "tab",
    "tabsPanelRightClickAction": "menu",
    "tabsPanelMiddleClickAction": "tab",
    "syncName": "",
    "syncSaveSettings": false,
    "syncSaveCtxMenu": false,
    "syncSaveStyles": false,
    "syncAutoApply": false
  },
  "permissions": {
    "allUrls": true,
    "tabHide": true,
    "actualAllUrls": true,
    "actualTabHide": true
  },
  "storage": {
    "size": "826.6 kb",
    "props": {
      "cssVars": "1.6 kb",
      "disabledKeybindings": "94 b",
      "favAutoCleanTime": "10 b",
      "favUrls": "39.8 kb",
      "favicons": "779.6 kb",
      "panelIndex": "1 b",
      "panels_v4": "378 b",
      "prevTabsData_v4": "1.5 kb",
      "profileID": "14 b",
      "settings": "2.5 kb",
      "sidebarCSS": "33 b",
      "tabsData_v4": "676 b"
    }
  },
  "panels": [
    {
      "type": "bookmarks",
      "id": "bookmarks",
      "cookieStoreId": "bookmarks",
      "name": 9,
      "icon": "...",
      "bookmarks": true,
      "lockedPanel": false
    },
    {
      "type": "default",
      "id": "firefox-default",
      "name": 7,
      "icon": "...",
      "cookieStoreId": "firefox-default",
      "lockedTabs": false,
      "lockedPanel": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true
    }
  ],
  "cssVars": {
    "nav_btn_width": "30px"
  },
  "sidebarCSSLen": 29,
  "windows": [
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 10
    }
  ],
  "bookmarks": {
    "bookmarksCount": 652,
    "foldersCount": 53,
    "separatorsCount": 2,
    "maxDepth": 4
  }
}
</code></details>

**Comment by mbnuqw** [comment]
Thanks for the report. As a workaround you can change shortcuts in the Add-ons Manager page "about:addons" (it hidden in the "gear" button menu).

**Comment by mbnuqw** [comment]
Fixed in v4.9.0

**Comment by ThaFog** [comment]
Seems like this bug still exists @mbnuqw

**Comment by mbnuqw** [comment]
@ThaFog, I cannot reproduce it. After disabling keybinding in sidebery settings page, it disappears from native keybindings menu (about:addons > top-right gears icon > Manage Extension Shortcuts) and there is no reaction on defined shortcut.

**Comment by tennox** [comment]
I can: :disappointed: 

https://user-images.githubusercontent.com/2084639/152191309-28f0d34a-d066-4682-9a63-e955b6191ca7.mp4

**Comment by albino1** [comment]
I just hit this bug, so FWIW it's still broken in 4.10.1.

I see the same behavior that @tennox's video shows.  If I disable a shortcut and then try and use it in another keybinding it errors out with Already Exists.

Does anyone know how to clear a keybinding and just reset it to `---`?  That would be a viable workaround, at least for my use case.

**Comment by tennox** [comment]
Just set it to a very unusual hotkey, I think that was my workaround

**Comment by albino1** [comment]
I worked around it using AutoHotKey, but that's a good idea as well.

I'm surprised there's no obvious way to just clear a key binding.

**Comment by mbnuqw** [comment]
You can press 'Delete' to remove focused keybinding. The issue itself will be fixed in v5.

**Comment by mbnuqw** [comment]
Fixed in the latest version
