### ISSUE TITLE
Tab tree randomly gets flattened

### ISSUE THREAD

**Issue by penyuan** [mbnuqw/sidebery#549]
## Steps to reproduce

* Open tabs in Firefox with the Sidebery extension
* Organize tabs into tree structure
* Close and re-open Firefox a few times
* Sometimes when you start Firefox, my tab tree has been flattened

## Expected behavior

* Tab tree to retain its structure after closing and restarting Firefox

## Actual behavior

* Tab tree gets flattened

## Environment info

OS:  Windows 10 21H2 and Red Hat Enterprise Linux 8.5 (this problem happens on both)
Firefox version:  95.0.2
Addon version:  4.10.0

<details><code>

Sorry I can't find a section called "Help" in my Settings page. Has its location changed?
</code></details>

**Comment by wotwot** [comment]
Additionally, all tabs from different groups get moved into the first one.     
OS: debian bullseye    
Firefox 95.0.2
Sidebery 4.10.0

**Comment by penyuan** [comment]
Update: This just happened to Firefox 95.0.2 on my Red Hat Enterprise Linux 8.5 system. The weird thing is, only *some* of my tabs got flattened, while others retained their tree structure!!! What's going on????

**Comment by arthurEspooner** [comment]
it's completely broken, trust me. the addon is nice but it doesn't respect tab order when reopening the browser, tree structure, it will undo closed tabs and insert them in random positions, the list goes on. i use this with a flat structure and a few different panels. you will pull your hair out after organizing a tree only to have it go flat.

**Comment by Lobachevskiy** [comment]
Toggle "global storage" to "session storage" in the settings/tabs. This fixed the issue for me and others.

**Comment by dexeonify** [comment]
Just to clarify, what are the exact steps to restore Sidebery tabs? There are currently 2 ways I can think of:

1. Close and reopen Firefox. Go to hamburger menu > History > Restore previous session
Sidebery never restores the tab tree and panels correctly no matter what I try. I've already tried using "session storage" and it's even reproducible in a new profile.

2. Go to `about:preferences` > Startup > Enable "Open previous windows and tabs". Close and reopen Firefox.
This works pretty reliably even with global storage. Session storage might make it more accurate, I guess.

Personally, I'm interested in No. 1 which is still inherently broken.

**Comment by penyuan** [comment]
@Lobachevskiy: Do you mean changing this within Sidebery settings under the "Tabs" section? It says "Tabs data will be removed along with Browser Session" which scares me. Does that mean I will lose my tabs as soon as I close Firefox? Or does it mean something else? What do I need to watch out for?

@dexeonify: For your option 2, what do you mean by "This works pretty reliably even with global storage". I have enabled "Open previous windows and tabs", but my tabs still randomly get flattened and lose their tree structure.

**Comment by dexeonify** [comment]
> For your option 2, what do you mean by "This works pretty reliably even with global storage". I have enabled "Open previous windows and tabs", but my tabs still randomly get flattened and lose their tree structure.

Idk, all I did was restarting and reopening Firefox ~10 times in a completely new profile, then check if the tab tree is correctly restored. My test isn't conclusive of course.

> BTW, is this addon still being maintained? Or is there a better replacement for it?

There are ongoing questions about this (#484 and #331). The addon is still being maintained (see version 4.10.0), however the development isn't very active currently. "Better" is subjective, I still prefer Sidebery for its features and customisability. There are always other vertical tabs extensions like Tree Style Tabs if you want to switch. :)

**Comment by SeerLite** [comment]
Using session storage broke multi-window for me (some windows showed errors and no tabs). This was a while ago so maybe it works fine now, but I haven't tested.

> Idk, all I did was restarting and reopening Firefox ~10 times in a completely new profile, then check if the tab tree is correctly restored. My test isn't conclusive of course.

To be fair, I've done the same with global storage (after changing some other setting to see if it was the cause) and gotten the same conclusions, only for the tree to flatten after a few days haha. But yeah, in my experience session storage doesn't have this issue at all, but as it broke multi-window for me I stopped using it.

**Comment by penyuan** [comment]
Thank you @dexeonify and @SeerLite for your insights, and glad to see that development work is still going on with thanks to the @mbnuqw and other contributors. I hope the maintainer/developer is aware of the IMO major problem discussed in this thread!

In the meantime, I'm considering (maybe temporarily) switching to another extension like Tree Style Tabs. In your opinion what are some major features of Sidebery that are lacking in other vertical tab extensions?

**Comment by wotwot** [comment]
> In the meantime, I'm considering (maybe temporarily) switching to another extension like Tree Style Tabs. In your opinion what are some major features of Sidebery that are lacking in other vertical tab extensions?

If I recall correctly Tree Tabs 2 did not work with containers enabled.

**Comment by penyuan** [comment]
> If I recall correctly Tree Tabs 2 did not work with containers enabled.

Do you mean the extension [Tree Tabs](https://addons.mozilla.org/en-GB/firefox/addon/tree-tabs/) or [Tree Style Tabs](https://addons.mozilla.org/en-GB/firefox/addon/tree-style-tab/)? They are *different* extensions. :)

**Comment by dexeonify** [comment]
In terms of "major features", probably the Bookmarks panel and tabs panels. It's just a combination of really nice features built-in that makes it a great extension (e.g. tabs unloading, tabs grouping/flatten, reopen in containers). It has better performance, looks nicer OOTB and most importantly allows me to change the preface value, so I can hide the tabs bar when Sidebery is active.

That said, Tree Style Tabs has *most* of these features as well, though I have to install 3 other extensions to replicate the functionalities in Sidebery. One thing I can definitely confirm is that restores tab very well (both No. 1 and No. 2 above).

v5 should make things more interesting, assuming the major bugs are fixed.

**Comment by wotwot** [comment]
> > If I recall correctly Tree Tabs 2 did not work with containers enabled.
> 
> Do you mean the extension [Tree Tabs](https://addons.mozilla.org/en-GB/firefox/addon/tree-tabs/) or [Tree Style Tabs](https://addons.mozilla.org/en-GB/firefox/addon/tree-style-tab/)? They are _different_ extensions. :) I was asking about Tree Style Tabs.

I think I meant [TreeTabs2](https://thomasmca.com/doku.php?id=blog:treetabs2) that at some point got me to switch to sidebery.

**Comment by penyuan** [comment]
> v5 should make things more interesting, assuming the major bugs are fixed.

Thanks! Cannot wait to try v5 (any timeline?), especially if this tab tree flattening problem gets fixed. 😄

**Comment by dexeonify** [comment]
I mean you can try it now (https://github.com/mbnuqw/sidebery/tree/v5). It's probably buggy though because it looks like a complete rewrite. Best to wait for the actual release, unless you want to help report bugs.

**Comment by brgr-m-r** [comment]
> Additionally, all tabs from different groups get moved into the first one.

> The weird thing is, only some of my tabs got flattened, while others retained their tree structure!!! What's going on????

I've been using Sidebery 5.0 for the last several months and that's still happening to some of the windows (not all) every now and then (rather disruptive, have to manually restore from snapshots each time).

Obviously, it would be great to understand the root cause and fix this mysterious issue 🙂

**Comment by Saya47** [comment]
So there's no way to undo when a random flattening happens? We have to restore backup?
