### ISSUE TITLE
New Tab Under Current Tree

### ISSUE THREAD

**Issue by haydenflinner** [mbnuqw/sidebery#95]
## Use cases
Have an idea while looking at one page, would like the search in a new tab to stay paired with the page that gave me the idea. E.g. looking at an email, would like to open up a bug tracker and make a search related to email.

Can code it if you give a few pointers for someone who's never opened the codebase 😃 

Btw, congrats on being the best looking, fastest, and least buggy treetabs implementation that I've found. A pity that it didn't come up when googling, I found it through the Tree Tabs GitHub README.

**Comment by haydenflinner** [comment]
Similarly, when opening tabs from a pinned tab, it would be nice to be able to create a tree just for those. Like a root tab called "Tabs from Gmail" and then the children are what I opened while reading emails.

**Comment by mbnuqw** [comment]
Sorry for the slow response, yeah, this looks reasonable. I'm planing to add options to handle new tab position and more keybindings for this.

**Comment by haydenflinner** [comment]
was a pretty quick response as far as open source goes :D I might start on this tomorrow, if you have any pointers as to where to start?

**Comment by mbnuqw** [comment]
Well, I already planned this feature for v3.2.0, which I hope will be available in 2-3 weeks, so you can just wait. For that version, I also planned the "Single panel mode" feature, which will allow you to open tabs of different containers in one panel (as it does in TreeStyleTabs and other vertical tabs addons). This mode will redefine the way of how sidebery handle/move just created tabs, so I think to implement "Single panel mode" first and then add the options to automatically move the created tab. So this is another reason to wait, just to not waste your time to write the code that I'll rewrite anyway.

About this feature itself - I'm still thinking of how it should be implemented. Maybe to add setting "Automatically move created tab" with next options:
- to the top of the panel
- to the bottom of the panel
- as the first child of the active tab
- as the last child of the active tab
- after the active tab (as a sibling)
- none - do nothing (current behavior), new tabs will be placed according to Firefox flags `browser.tabs.insertAfterCurrent`, `browser.insertRelatedAfterCurrent`... etc.
Or maybe even, add three different settings: for tabs opened from pinned tab, for tabs opened from normal tabs and for tabs opened without any relation (e.g. new tab created with ctrl t).
Any thoughts about how it should look are welcomed.

**Comment by haydenflinner** [comment]
I see promising stuff in the dev branch, thanks so much! And now that I'm here I see you marked it done, even cooler! I will see if I can run this dev version tomorrow when I get into work.

**Comment by mbnuqw** [comment]
Yes, I've implemented new tab position handling, but there are still so many bugs, so be prepared ;).
Also, in 3.2.0 I changed the structure of stored data, but not yet write the function for converting it on an update, so be sure to run it on clean FF.

Any feedback, suggestions and thoughts are welcomed!

**Comment by haydenflinner** [comment]
I did indeed find plenty of bugs. I didn't run on a clean Firefox, I just closed most of my tabs (all but the pinned tabs), which got the sidebar to recognized my pinned tabs and put them at the top.
A few problems:
  * Opening a new tab with CTRL+T still doesn't open as a child, I have to double click the current tab to do that
  * I have a "<Tab Number> -" prefix on every tab
  * I can't rearrange the tabs, like to move them around the list or into a tree. Holding the mouse button on them doesn't cause them to enter the "floating" visual, they just stay looking like I haven't clicked them.
  * By the end of the workday, my pinned tabs had vanished from the panel (except for the first one) and I could only open them by clicking in the actual Firefox tab switcher

Tomorrow I will try closing all of my tabs and restarting the browser to see if a clean slate helps. Otherwise I might switch back to TST in the meantime until this feature is released since I fixed the monitor issue I had which made TST take up way too much screen, lol.

**Comment by haydenflinner** [comment]
Hey, closed all my tabs and restarted and it behaved much better today. Could drag tabs around as expected. No bugs that I hit. Still couldn't get CTRL+T to work; if I recall on other plugins this required giving perms to access my pages' data? Or maybe that was to hook CTRL+TAB to change the active tab? Either way I checked that option and allowed permissions, still no dice.

**Comment by mbnuqw** [comment]
To fix some of the bugs you can try clean up addon data. You can do this in sidebery settings page (section storage - just remove all items one by one) or just run `browser.storage.local.clear()` in the debugger and re-enable addon.

About CTRL+T behavior - right now, its possible to place a new tab (opened with ctrl+t) as a sibling after the current one, but I can also add an option 'as a child of active tab' to the setting 'Place new tab (for the other cases)'. But this also applies to all new tabs that were open from outside of Firefox. Unfortunately, there is no way to detect any native(default) shortcuts including ctrl+t. Plus as a workaround, I can add special keybindings/buttons for this case (like "Open new tab as (first/last) child of active tab").

I'll write here, after I'll add this option.

**Comment by haydenflinner** [comment]
just deleting all of the open tabs and starting fresh seemed to be enough. Has been stable for the week since. thanks for all of your work on the plugin :)

**Comment by mbnuqw** [comment]
I've just pushed to dev new options for placing new tabs as first/last child, plus keybindings: a466aeb,  d0111e0,  cd7d103

**Comment by haydenflinner** [comment]
I think I see where the option -would- be, but it's not there. Also, the Keybindings menu cleared itself so it only contains the title "Keybindings" and the button "Reset Keybindings". No items in there like when I was on master. I've ran the console command to clear local storage from the preferences page as well as clicking Reset Settings at the bottom of the page. Thanks for the commits to add the new feature though!
![image](https://user-images.githubusercontent.com/14845292/70091572-66d53200-15ea-11ea-9aa8-40d951264095.png)

**Comment by mbnuqw** [comment]
You can try to `npm run clear` to remove assets from previous build and then `npm run build` again.
Also don't forget about cleaning out addon's data (with the `browser.storage.local.clear()` in the debugger) there are changes in the dev branch that can lead to such behavior.

**Comment by haydenflinner** [comment]
Will give that a shot, I thought I was in the clear because I built in fresh folder, but I forgot that I built from master first before building dev. I did clear local storage though.

**Comment by mbnuqw** [comment]
Since 'New-tab position' feature was landed in v4.x.x I'm closing this issue.
